# Generated by Django 4.2.16 on 2026-06-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='sandbox', max_length=50, verbose_name='Gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=200, verbose_name='ID no gateway')),
                ('gateway_status', models.CharField(blank=True, max_length=50, verbose_name='Status no gateway')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='Método')),
                ('payment_link', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('pix_code', models.TextField(blank=True, verbose_name='Código PIX copia-e-cola')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX (base64)')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta do gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
