# Generated by Django 4.2.16 on 2026-06-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(verbose_name='Data da viagem')),
                ('order_deadline', models.DateField(verbose_name='Data limite para encomendas')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem personalizada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Próxima viagem',
                'verbose_name_plural': 'Próximas viagens',
                'ordering': ['-trip_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='ParaguaShopping', max_length=100, verbose_name='Nome da loja')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='Logo')),
                ('whatsapp', models.CharField(default='', max_length=20, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep_origem', models.CharField(blank=True, max_length=9, verbose_name='CEP de origem')),
                ('home_headline', models.CharField(default='Produtos importados selecionados', max_length=200, verbose_name='Chamada principal da home')),
                ('home_subheadline', models.TextField(blank=True, default='Com pronta entrega e encomendas mensais.', verbose_name='Subtexto da home')),
                ('about_text', models.TextField(blank=True, verbose_name='Texto sobre a loja')),
                ('order_mode_active', models.BooleanField(default=True, verbose_name='Modo encomenda ativo')),
                ('shipping_active', models.BooleanField(default=True, verbose_name='Frete ativo')),
                ('payment_gateway', models.CharField(default='sandbox', max_length=50, verbose_name='Gateway de pagamento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurações da loja',
                'verbose_name_plural': 'Configurações da loja',
            },
        ),
    ]
