# Generated by Django 4.2.16 on 2026-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storesettings_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(default='USD', max_length=10, verbose_name='De')),
                ('currency_to', models.CharField(default='BRL', max_length=10, verbose_name='Para')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cotação')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fonte')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='Essence K Importados', max_length=100, verbose_name='Nome da loja'),
        ),
    ]
