# Generated by Django 4.2.16 on 2026-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storedmediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Título (opcional)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Texto/descrição (opcional)')),
                ('image', models.ImageField(upload_to='showcase/', verbose_name='Imagem')),
                ('link', models.CharField(blank=True, help_text='URL para onde o slide leva ao clicar. Ex: /produtos/', max_length=500, verbose_name='Link (opcional)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide do Showcase',
                'verbose_name_plural': 'Slides do Showcase',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
