# Generated by Django 4.2.16 on 2026-07-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_brand_created_at"),
        ("core", "0006_showcase_slide"),
    ]

    operations = [
        migrations.AddField(
            model_name="showcaseslide",
            name="background_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("preto-dourado", "Preto & Dourado"),
                    ("rosa-nude", "Rosa Nude"),
                    ("vinho", "Vinho Profundo"),
                    ("azul-noite", "Azul Noite"),
                    ("esmeralda", "Verde Esmeralda"),
                    ("nude", "Nude Elegante"),
                ],
                default="preto-dourado",
                max_length=20,
                verbose_name="Estilo de fundo",
            ),
        ),
        migrations.AddField(
            model_name="showcaseslide",
            name="kind",
            field=models.CharField(
                choices=[
                    ("product", "Produto do estoque"),
                    ("text", "Texto / Promoção"),
                    ("image", "Imagem manual (legado)"),
                ],
                default="image",
                max_length=10,
                verbose_name="Tipo de slide",
            ),
        ),
        migrations.AddField(
            model_name="showcaseslide",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showcase_slides",
                to="products.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="showcaseslide",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="showcase/", verbose_name="Imagem"
            ),
        ),
    ]
