# Generated by Django 4.2.16 on 2026-06-26 10:54

from django.db import migrations, models
import django.db.models.functions.text
import re


ONLY_DIGITS_RE = re.compile(r'\D+')


def only_digits(value):
    return ONLY_DIGITS_RE.sub('', value or '')


def normalize_whatsapp(value):
    digits = only_digits(value)
    if digits.startswith('55') and len(digits) in (12, 13):
        digits = digits[2:]
    return digits or None


def normalize_existing_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen_emails = {}
    seen_whatsapps = {}
    updates = []

    for user in User.objects.all().order_by('pk'):
        email = (user.email or '').strip().casefold()
        if not email:
            raise ValueError(
                'Existem usuários sem e-mail. Preencha e-mails únicos antes de aplicar esta migração.'
            )
        if email in seen_emails:
            raise ValueError(
                f'E-mail duplicado ao normalizar: {email}. Ajuste os usuários {seen_emails[email]} e {user.pk}.'
            )
        seen_emails[email] = user.pk

        whatsapp = normalize_whatsapp(user.whatsapp)
        if whatsapp:
            if whatsapp in seen_whatsapps:
                raise ValueError(
                    f'WhatsApp duplicado ao normalizar: {whatsapp}. Ajuste os usuários {seen_whatsapps[whatsapp]} e {user.pk}.'
                )
            seen_whatsapps[whatsapp] = user.pk

        user.email = email
        user.username = email
        user.whatsapp = whatsapp
        updates.append(user)

    User.objects.bulk_update(updates, ['email', 'username', 'whatsapp'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.RunPython(normalize_existing_users, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='WhatsApp'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
    ]
