# Generated by Django 4.2.16 on 2026-07-02 13:51

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cpf_alter_user_email_alter_user_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_encrypted',
            field=core.encryption.EncryptedCharField(max_length=200, verbose_name='CPF criptografado'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_encrypted',
            field=core.encryption.EncryptedCharField(max_length=200, verbose_name='WhatsApp criptografado'),
        ),
    ]
