# Generated by Django 4.2.16 on 2026-07-04 23:07

import core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cpf_encrypted_user_whatsapp_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_encrypted',
            field=core.encryption.EncryptedCharField(max_length=200, verbose_name='Telefone criptografado'),
        ),
    ]
