# Generated by Django 4.2.16 on 2026-06-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('carrier', models.CharField(default='Correios', max_length=100, verbose_name='Transportadora')),
                ('service', models.CharField(max_length=50, verbose_name='Serviço')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('min_days', models.PositiveIntegerField(default=1, verbose_name='Prazo mínimo (dias)')),
                ('max_days', models.PositiveIntegerField(default=10, verbose_name='Prazo máximo (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tabela de frete',
                'verbose_name_plural': 'Tabela de fretes',
            },
        ),
    ]
