# Generated by Django 4.2.16 on 2026-06-26 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.generate_order_number, max_length=20, unique=True, verbose_name='Número do pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('customer_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de crédito'), ('whatsapp', 'Finalizar pelo WhatsApp')], default='pix', max_length=20, verbose_name='Forma de pagamento')),
                ('payment_status', models.CharField(default='pending', max_length=50, verbose_name='Status do pagamento')),
                ('payment_link', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID pagamento gateway')),
                ('status', models.CharField(choices=[('created', 'Pedido criado'), ('awaiting_payment', 'Aguardando pagamento'), ('payment_confirmed', 'Pagamento confirmado'), ('partial_confirmed', 'Parcialmente confirmado'), ('separating', 'Em separação'), ('partial_shipped', 'Parcialmente enviado'), ('shipped', 'Enviado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='awaiting_payment', max_length=30, verbose_name='Status')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='Código de rastreio')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Transportadora')),
                ('tracking_url', models.URLField(blank=True, verbose_name='Link de rastreio')),
                ('shipping_service', models.CharField(blank=True, max_length=100, verbose_name='Serviço de envio')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Observações do cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagamento confirmado em')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('status', models.CharField(choices=[('received', 'Solicitação recebida'), ('awaiting_admin', 'Aguardando confirmação da admin'), ('confirmed', 'Produto confirmado'), ('awaiting_payment', 'Aguardando pagamento'), ('paid', 'Pago'), ('awaiting_arrival', 'Aguardando chegada'), ('ready_to_ship', 'Disponível para envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='received', max_length=30, verbose_name='Status')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor combinado')),
                ('payment_link', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nexttrip', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('product_brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('is_pre_order', models.BooleanField(default=False, verbose_name='Sob encomenda')),
                ('item_status', models.CharField(choices=[('ready', 'Pronta entrega'), ('pre_order', 'Sob encomenda'), ('awaiting', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('paid', 'Pago'), ('separating', 'Em separação'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='ready', max_length=20, verbose_name='Status do item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
