# Generated by Django 4.2.16 on 2026-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cotação USD/BRL'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal USD'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total USD'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço unit. USD'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Variação'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume ml'),
        ),
    ]
