# Generated by Django 4.2.16 on 2026-07-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_category_parent_product_cost_price_usd_and_more'),
        ('orders', '0002_order_exchange_rate_order_subtotal_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='Variação'),
        ),
    ]
