# Generated by Django 4.2.16 on 2026-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de crédito')], default='pix', max_length=20, verbose_name='Forma de pagamento'),
        ),
    ]
