# Generated by Django 4.2.16 on 2026-07-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_whatsapp',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='preorderrequest',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
