# Generated by Django 4.2.16 on 2026-08-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('whatsapp', 'A combinar pelo WhatsApp'), ('pix', 'Pix'), ('credit_card', 'Cartão de crédito')], default='whatsapp', max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Pedido criado'), ('awaiting_contact', 'Aguardando confirmação no WhatsApp'), ('awaiting_payment', 'Aguardando pagamento'), ('payment_confirmed', 'Pagamento confirmado'), ('partial_confirmed', 'Parcialmente confirmado'), ('separating', 'Em separação'), ('partial_shipped', 'Parcialmente enviado'), ('shipped', 'Enviado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='awaiting_contact', max_length=30, verbose_name='Status'),
        ),
    ]
