# Generated by Django 4.2.16 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('whatsapp', 'Pagamento não definido (pedido anterior)'),
                    ('pix', 'Pix'),
                    ('credit_card', 'Cartão de crédito'),
                ],
                default='pix',
                max_length=20,
                verbose_name='Forma de pagamento',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Pedido criado'),
                    ('awaiting_contact', 'Aguardando definição de pagamento'),
                    ('awaiting_payment', 'Aguardando pagamento'),
                    ('payment_confirmed', 'Pagamento confirmado'),
                    ('partial_confirmed', 'Parcialmente confirmado'),
                    ('separating', 'Em separação'),
                    ('partial_shipped', 'Parcialmente enviado'),
                    ('shipped', 'Enviado'),
                    ('completed', 'Concluído'),
                    ('cancelled', 'Cancelado'),
                ],
                default='awaiting_payment',
                max_length=30,
                verbose_name='Status',
            ),
        ),
    ]
