# Generated by Django 5.2.17 on 2026-09-27 17:03

import core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_official_online_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_lookup',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='phone_lookup',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_whatsapp',
            field=core.encryption.EncryptedCharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='preorderrequest',
            name='whatsapp',
            field=core.encryption.EncryptedCharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
