# Generated by Django 4.2.16 on 2026-06-26 02:31

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descrição curta')),
                ('description', models.TextField(blank=True, verbose_name='Descrição completa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de venda')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de custo (interno)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque real')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('low_stock', 'Últimas unidades'), ('pre_order', 'Sob encomenda'), ('out_of_stock', 'Esgotado')], default='available', max_length=20, verbose_name='Status público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='Promoção')),
                ('is_pre_order', models.BooleanField(default=False, verbose_name='Sob encomenda')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Altura (cm)')),
                ('width', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Largura (cm)')),
                ('length', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Comprimento (cm)')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_path, verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Foto principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens do produto',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
