# Generated by Django 4.2.16 on 2026-07-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Categoria pai'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo USD'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GTIN/EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Tem variações'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fractioned',
            field=models.BooleanField(default=False, verbose_name='Perfume fracionado'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço USD'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promo USD'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome da variação')),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume (ml)')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Cor')),
                ('size', models.CharField(blank=True, max_length=80, verbose_name='Tamanho')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço USD')),
                ('promotional_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promo USD')),
                ('cost_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo USD')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU')),
                ('gtin', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GTIN/EAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['order', 'volume_ml', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Marca'),
        ),
    ]
