# Generated by Django 4.2.30 on 2026-08-07 00:47

from django.db import migrations, models
import django.db.models.deletion


def seed_home_collections(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    HomeCollection = apps.get_model('products', 'HomeCollection')

    definitions = [
        {
            'key': 'ofertas',
            'title': 'Ofertas',
            'route_slug': 'ofertas',
            'description': 'Produtos com desconto valido.',
            'kind': 'offers',
            'order': 10,
        },
        {
            'key': 'perfumes-de-nicho',
            'title': 'Perfumes de Nicho',
            'route_slug': 'perfumes-de-nicho',
            'description': 'Perfumes importados selecionados.',
            'kind': 'category',
            'order': 20,
            'category_slugs': ['perfumes-importados-nicho'],
        },
        {
            'key': 'beleza-coreana',
            'title': 'Beleza Coreana',
            'route_slug': 'beleza-coreana',
            'description': 'Skincare coreano para a sua rotina.',
            'kind': 'category',
            'order': 30,
            'category_slugs': ['Skincare-coreano'],
        },
        {
            'key': 'decanter',
            'title': 'Decanter',
            'route_slug': 'decanter',
            'description': 'Escolha entre Decanter 5 ml e 10 ml.',
            'kind': 'category',
            'order': 40,
        },
        {
            'key': 'decanter-5ml',
            'title': 'Decanter 5 ml',
            'route_slug': 'decanter-5ml',
            'description': 'Frascos de 5 ml.',
            'kind': 'category',
            'order': 41,
            'parent_key': 'decanter',
            'is_home_visible': False,
            'category_slugs': ['Perfume-fracionado-decanter5ml'],
        },
        {
            'key': 'decanter-10ml',
            'title': 'Decanter 10 ml',
            'route_slug': 'decanter-10ml',
            'description': 'Frascos de 10 ml.',
            'kind': 'category',
            'order': 42,
            'parent_key': 'decanter',
            'is_home_visible': False,
            'category_slugs': ['Perfume-fracionado-decanter10ml'],
        },
        {
            'key': 'suplementos',
            'title': 'Suplementos',
            'route_slug': 'suplementos',
            'description': 'Saude e bem-estar em preparacao.',
            'kind': 'category',
            'order': 50,
            'category_slugs': ['suplementos-saude-bem-estar'],
        },
        {
            'key': 'destaques',
            'title': 'Destaques',
            'route_slug': 'destaques',
            'description': 'Produtos selecionados pela Essence K.',
            'kind': 'featured',
            'order': 60,
        },
        {
            'key': 'pronta-entrega',
            'title': 'Pronta Entrega',
            'route_slug': 'pronta-entrega',
            'description': 'Produtos disponiveis para envio agora.',
            'kind': 'available',
            'order': 70,
        },
    ]

    collections_by_key = {}
    for definition in definitions:
        parent_key = definition.pop('parent_key', '')
        category_slugs = definition.pop('category_slugs', [])
        parent = collections_by_key.get(parent_key)
        defaults = {
            **definition,
            'parent': parent,
        }
        collection, _ = HomeCollection.objects.get_or_create(
            key=definition['key'], defaults=defaults,
        )
        collections_by_key[collection.key] = collection
        for category_slug in category_slugs:
            category = Category.objects.filter(slug__iexact=category_slug).first()
            if category:
                collection.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_brand_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='Chave interna')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('route_slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug da rota')),
                ('description', models.CharField(blank=True, max_length=180, verbose_name='Descricao')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-collections/', verbose_name='Imagem')),
                ('kind', models.CharField(choices=[('category', 'Categorias vinculadas'), ('offers', 'Ofertas com desconto valido'), ('featured', 'Produtos em destaque'), ('available', 'Pronta entrega')], max_length=20, verbose_name='Regra de produtos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_home_visible', models.BooleanField(default=True, verbose_name='Exibir na Home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('categories', models.ManyToManyField(blank=True, related_name='home_collections', to='products.category', verbose_name='Categorias vinculadas')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.homecollection', verbose_name='Colecao pai')),
            ],
            options={
                'verbose_name': 'Colecao da Home',
                'verbose_name_plural': 'Colecoes da Home',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RunPython(seed_home_collections, migrations.RunPython.noop),
    ]
